name: deploy-build-react
on:
  push:
    branches: main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name : pwd
        run : ls > ls.txt
      - name : test
        run : cat ls.txt
